### ISSUE TITLE
(38)Function not implemented: AH00141: Could not initialize random number generator

### ISSUE THREAD

**Issue by deecav** [adamzammit/limesurvey-docker#24]
I'm running version 5.1.14
Docker API version 1.26
OS Version: Ubuntu 14.04.5 LTS  (yes I know it's EOL, but I didn't think that would be causing this error)

Getting this critical error when trying to start the container.  Have you seen this before or know if there is a work around?

This is the full output from running "docker logs" on the container

```
Copying default container default config files into config volume...
No index.html file upload dir in /var/www/html Copying defaults...
Updating password for admin user
Password for user admin was set.
Flushing assets in /var/www/html/tmp
[Tue Oct 05 14:45:54.233787 2021] [:crit] [pid 1] (38)Function not implemented: AH00141: Could not initialize random number generator
```

Here's the compose file:

```
  limesurvey5:
    image: acspri/limesurvey:5.1.14
    container_name: limesurvey_lime5
    ports:
      - "8082:80"
    environment:
      - "LIMESURVEY_DB_HOST=*****************************.rds.amazonaws.com"
      - "LIMESURVEY_DB_NAME=limesurvey5"
      - "LIMESURVEY_DB_USER=*********"
      - "LIMESURVEY_DB_PASSWORD=***********************"
      - "LIMESURVEY_TABLE_PREFIX=lime_"
      - "LIMESURVEY_ADMIN_USER=********"
      - "LIMESURVEY_ADMIN_PASSWORD=*************************"
      - "LIMESURVEY_ADMIN_EMAIL=admin@sample.com"
      - "LIMESURVEY_ADMIN_NAME=Admin User"
      - "LIMESURVEY_DEBUG=2"
    restart: always
    volumes:
      - ./plugins:/var/www/html/plugins
      - ./upload:/var/www/html/upload
      - ./config:/var/www/html/application/config
```
