### ISSUE TITLE
unable to start limesurvey container: syntax error in config.php

### ISSUE THREAD

**Issue by tubia** [adamzammit/limesurvey-docker#33]
**Images tested: `5.3.27`, `5.3.28`**

Hi,

I used the `docker-compose.yml` template suggested in the repo to setup an instance of limesurvey.

Unfortunately, I got an error when I launch the containers, in the limesurvey container:

```
Parse error: syntax error, unexpected identifier "iE209", expecting ")" in /var/www/html/application/config/config.php on line 32
```

Any hint on what could it be?

**Comment by adamzammit** [comment]
Hi @tubia .

I can't replicate that here. Can you please confirm you haven't edited the configuration file?

Please try from a new blank directory or remove the config subdirectory from the local filesystem where the docker-compose file is located.

Adam

**Comment by tubia** [comment]
Hi Adam,
thank you for your reply.

It was an issue with some password chars.

Now the error has been fixed, but I have a new one in the Limesurvey container: `MySQL Connection Error: ()`

This is the `docker-compose.yml` I am using:

```yaml
version: '2'

services:

  limesurvey:
    image: acspri/limesurvey:5.3.28
    depends_on:
      - mysql
    ports:
      - 8082:80
    environment:
      LIMESURVEY_DB_PASSWORD: <pwd>
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: <pwd2>
      LIMESURVEY_ADMIN_NAME: Administrator
      LIMESURVEY_ADMIN_EMAIL: <name>
    volumes:
      - /srv/limesurvey/plugins:/var/www/html/plugins
      - /srv/limesurvey/upload:/var/www/html/upload
      - /srv/limesurvey/config:/var/www/html/application/config

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: <pwd>
```
