### ISSUE TITLE
Cannot access backend with nginx reverse proxy

### ISSUE THREAD

**Issue by keschyfoo** [adamzammit/limesurvey-docker#37]
I am using a pretty basic nginx reverse proxy config for my SSL setup.

Unfortunately the limesurvey admin-backend always redirects to `http://limesurvey/admin/` when I am trying to access `survey.mydomain.com/admin`. 

My nginx compose setup:

```
nginx:
   container_name: limesurvey_proxy
   restart: always
   image: nginx
   volumes:
   - /etc/containers/limesurvey/nginx.conf:/etc/nginx/nginx.conf:ro
   - /etc/containers/limesurvey/limesite.conf:/etc/nginx/conf.d/default.conf:ro
   - /etc/containers/limesurvey/certs:/etc/nginx/certs
   - /opt/limesurvey/nginx-logs:/var/log/nginx
   ports:
   - 443:443
   links:
   - limesurvey
   networks:
     limenetwork_compose:
   command: /bin/bash -c "nginx -g 'daemon off;'"

```

the relevant nginx config:

```
server {
    listen       443 ssl http2;
    server_name <FQDN>;

        ssl_certificate     /etc/nginx/certs/crt.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_session_cache shared:SSL:10m;
        ssl_session_tickets off;
        ssl_stapling off;
        ssl_stapling_verify off;

    location / {
    proxy_pass http://limesurvey:80/;
    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    access_log off;
    client_max_body_size 4096m;
}
```

The surveys work fine with the reverse proxy and the default start page also loads fine. Only the admin-backend is not working properly.

Is there any way to fix this issue?
