### ISSUE TITLE
Why I am getting this error?

### ISSUE THREAD

**Issue by elhossary** [adamzammit/limesurvey-docker#50]
I am using the latest docker image, after I log in with the admin username for the first use I get this error:
![Screenshot_20240119_121527](https://github.com/adamzammit/limesurvey-docker/assets/12513051/89bce5a1-1eab-4ac5-9356-894b41b19960)

**Comment by adamzammit** [comment]
Apologies for the delayed response @elhossary  - are you still seeing this in the latest version? If so could you please send through your docker-compose file?

**Comment by elhossary** [comment]
@adamzammit, thanks
Yes in the latest, happens directly after successful login
```
---
version: '3'

services:
  limesurvey:
    container_name: limesurvey
    image: adamzammit/limesurvey
    restart: unless-stopped
    ports:
      - 8083:80
    depends_on:
      - limesurvey_db
    networks:
      - limesurvey_net
    environment:
      - LIMESURVEY_DB_HOST=limesurvey_db
      - LIMESURVEY_DB_NAME=limesurvey
      - LIMESURVEY_DB_USER=limesurvey
      - LIMESURVEY_TABLE_PREFIX=ls_
      - LIMESURVEY_DB_PASSWORD=<pass>
      - LIMESURVEY_ADMIN_USER=elhossary
      - LIMESURVEY_ADMIN_PASSWORD=<pass>
      - LIMESURVEY_ADMIN_NAME=<name>
      - LIMESURVEY_ADMIN_EMAIL=<email>
      - LIMESURVEY_DEBUG=2
      - LIMESURVEY_SQL_DEBUG=2
    volumes:
      - /vol/limesurvey/plugins:/var/www/html/plugins
      - /vol/limesurvey/upload:/var/www/html/upload
      - /vol/limesurvey/config:/var/www/html/application/config

  limesurvey_db:
    container_name: limesurvey_db
    restart: unless-stopped
    image: mariadb
    ports:
      - 3307:3306
    networks:
      - limesurvey_net
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=false
      - MYSQL_ROOT_PASSWORD=<pass>
      - MYSQL_PASSWORD=<pass>
      - MYSQL_DATABASE=limesurvey
      - MYSQL_USER=limesurvey
    volumes:
      - /var/lib/limesurvey_db:/var/lib/mysql

networks:
  limesurvey_net:
    name: limesurvey_net
    driver: bridge
```
