### ISSUE TITLE
Everything disappears each time the container restarts...

### ISSUE THREAD

**Issue by mnfctrdinitaly** [adamzammit/limesurvey-docker#57]
I have mounted the following paths

```yaml
    volumes:
      - /docker/ccea/lime/uploads:/var/www/html/upload
      - /docker/ccea/lime/plugins:/var/www/html/plugins
      - /docker/ccea/lime/config:/var/www/html/application/config
      - /docker/ccea/lime/session:/var/lime/sessions
```

And yet, everything erases every time I stop and start the stack. I don't know what I am doing wrong...

Additionally, anytime I change a global config setting instead of a green success modal popup I get a red warning/error without any text and nothing shows in the logs.

**Comment by adamzammit** [comment]
can you please share your full docker-compose file.

When you say "everything erases" do you mean the files or the LimeSurvey content such as surveys? LimeSurvey stores most data in the database so please ensure that the database container volume will persist.

**Comment by mnfctrdinitaly** [comment]
Thanks for the response!

> please ensure that the database container volume will persist

That might be my issue... what is the volume that contains the db? Here's the complete compose

```yaml
version: '2'
services:
  limesurvey:
    image: adamzammit/limesurvey
    container_name: ccea-lime
    networks:
      - cceadockernet
    restart: always
    expose:
      - 80
    environment:
      LIMESURVEY_DB_HOST: ccea-lime-db
      LIMESURVEY_DB_PASSWORD: secret
      LIMESURVEY_ADMIN_USER: secret
      LIMESURVEY_ADMIN_PASSWORD: secret
      LIMESURVEY_ADMIN_NAME: secret
      LIMESURVEY_ADMIN_EMAIL: secret
      LIMESURVEY_FROM_EMAIL: secret
      LIMESURVEY_SMTP_HOST: secret
      LIMESURVEY_SMTP_USER: secret
      LIMESURVEY_SMTP_PASSWORD: secret
      LIMESURVEY_SMTP_SSL: ssl
      LIMESURVEY_DEBUG: 1
    volumes:
      - /docker/ccea/lime/uploads:/var/www/html/upload
      - /docker/ccea/lime/plugins:/var/www/html/plugins
      - /docker/ccea/lime/config:/var/www/html/application/config
      - /docker/ccea/lime/session:/var/lime/sessions
  mysql:
    image: mariadb:10.5
    container_name: ccea-lime-db
    networks:
      - cceadockernet
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
networks:
  cceadockernet:
    external: true
```

I'm guessing that I need another volume bind in the mysql service? 

Additionally, I renamed the container so that I can differentiate it from another instance running on the same host. Is that possibly an issue?
